### ISSUE TITLE
Use nonce on Entity in update property values

### ISSUE THREAD

**Issue by siman** [Joystream/substrate-versioned-store-module#19]
We need to introduce and use `nonce` during updates to Entity properties to prevent race conditions.

**Comment by siman** [comment]
Here is an example:
- On UI you can reorder a list of tracks in an album (or a list of videos in a playlist). This can also include adding or removing new items (tracks) to the album.
- Then send a single tx with this reorganized list of tracks.

The main idea is not to send each time a tx when we change a position of a track in the album. So to prevent race conditions we need to introduce an incrementable `nonce` field to Entity.

**Comment by bedeho** [comment]
One clarification from discussions: This is really only for when we possibly have property values that are vector types, and we support direct vector operations, like `add`,`pop`, `insert` etc. as suggested in #13 .

**Comment by bedeho** [comment]
Just moved the whole point into https://github.com/Joystream/substrate-versioned-store-module/issues/13, since we currently don't have such vector update operations.
